# translate bitbucket terms to desired
# github labels.   setting to null means the
# label will be removed
label_translations:
  "proposal": "feature"
  "enhancement": "feature"
  "trivial": "easy"
  "critical": "high priority"
  "major": null
  "minor": "low priority"

# bitbucket issue states that should be converted
# into labels.  note the label_translations take
# affect for these *after* they are looked up in this list.
states_as_labels:
  - "wontfix"
  - "on hold"
  - "duplicate"
  - "invalid"

github_user_badge_template: |
  GitHub: [{gh_user}](https://github.com/{gh_user})

bitbucket_user_badge_template: |
  Bitbucket: [{bb_user}](https://bitbucket.org/{bb_user})

user_template: |
  {display_name} ({bb_user_badge} {gh_user_badge})

issue_template: |
  **[Original report](https://bitbucket.org/{repo}/issue/{id}) by {reporter}.**

  {attachments}{sep}

  {content}

issue_template_skip_user: |
  **[Original report](https://bitbucket.org/{repo}/issue/{id}) by me.**

  {attachments}{sep}

  {content}

names_only_attachments_template: |
  The original report had attachments: {attachment_names}


linked_attachments_template: |
  Attachments: {attachment_links}


comment_template: |
  **Original comment by {author}.**

  {sep}

  {content}

comment_template_skip_user: |
  {content}

change_template: |
  **Original changes by {author}.**

  {sep}

  {changes}
